### ISSUE TITLE
Extend subscription and notification service

### ISSUE THREAD

**Issue by uklotzde** [kartevonmorgen/openfairdb#194]
Currently all e-mails (signup, subscription, password reset) are dispatched to a local `sendmail` instance. This has various restrictions and drawbacks:

- Poor performance, i.e. one external process invocation per e-Mail
- The synchronous invocation doesn't scale
- Sending e-mails doesn't work within the Docker container and is disabled

The current implementation should be replaced by dispatching the sending of e-mails to a service provider.

Overview: https://konghq.com/blog/list-of-10-email-apis/

- [MailGun](https://www.mailgun.com/)
- [SendGrid](http://sendgrid.com/)
- [Mandrill](http://mandrill.com/)
- [mailjet](https://www.mailjet.com/email-api/)
- [MailChimp](https://mailchimp.com/)
- ...

The implementation should define an abstract interfaces that allow switching from one provider to another if required and doesn't introduce any dependencies on the actual API into the use cases.

Related issues:
- kartevonmorgen/openfairdb#166 Decouple post-processing from requests
- kartevonmorgen/openfairdb#172 Email-format issue
- kartevonmorgen/kvmflows#9 Send notifications as daily summary
- kartevonmorgen/kvmflows#4 Add link to unsubscribe in notification mail
- kartevonmorgen/openfairdb#95 Changes in email-texts
- kartevonmorgen/openfairdb#68 Support email templates

## ToDo's
- [x] Design overall architecture 
- [x] Create a components diagram
- [x] Implement it
- [x] https://github.com/kartevonmorgen/openfairdb/pull/259

**Comment by uklotzde** [comment]
All the subscriptions and notifications should be handled by an external service. After the introduction of `GET /entries/recently-added` in kartevonmorgen/openfairdb#198 this is now possible.

**Comment by wellemut** [comment]
E-Mail API gateway is done, https://github.com/kartevonmorgen/openfairdb/pull/259
but not in use yet. Our server still sends mails directly. Needs to change.

**Comment by wellemut** [comment]
@magdaddy What is the state of this issue at the moment?

**Comment by wellemut** [comment]
@navid-kalaei has made these improvements, and rewrote the whole scypt in python: https://github.com/kartevonmorgen/kvmworkflows

The Service 

1. Pulls all changes happening in ofDB in an own DB
2. Analyses it in comparisson with subscriptions
3. Sends the mails via mailgun.

@navid-kalaei when you write the Readme, it would be nice if you could

- [ ] Create a components diagram (which explains the overall architecture)
