### ISSUE TITLE
Daily/hourly crawler for subscription- & notification service(s)

### ISSUE THREAD

**Issue by uklotzde** [kartevonmorgen/openfairdb#202]
Subscriptions and notifications are a separate domain that is independent of the geographical mapping of places and events. 

- [x] All subscriptions should be handled by a separate service that periodically polls OpenFairDB for changes (hourly, daily). Even independent subscription services for different use cases are possible. https://github.com/kartevonmorgen/openfairdb/issues/166

- [x] OpenFairDB should provide extension points in the form of an API that enables this decompositions. One request is already available: kartevonmorgen/openfairdb#198

- [x] All subscriptions and notifications should be removed from OpenFairDB. This make kartevonmorgen/openfairdb#194 obsolete.

**Comment by wellemut** [comment]
Seems to be a duplicate of: https://github.com/kartevonmorgen/openfairdb/issues/194

**Comment by wellemut** [comment]
This is an alternative: https://github.com/kartevonmorgen/openfairdb/issues/166

**Comment by wellemut** [comment]
This is going to be solved soon by @magdaddy . Its exactly the why he is doing it by using the "recently changed api" https://github.com/kartevonmorgen/kvmflows/issues/8#issuecomment-894298571

**Comment by wellemut** [comment]
All is solved in this new script: https://github.com/kartevonmorgen/kvmflows/releases/tag/v0.0.0
